# Generated by Django 5.1.2 on 2024-11-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.CharField(max_length=80, verbose_name='1era Pegunta Secreta')),
                ('answer_1', models.CharField(max_length=50, verbose_name=' Respuesta Secreta')),
                ('question_2', models.CharField(max_length=100, verbose_name='2da Pregunta Secreta')),
                ('answer_2', models.CharField(max_length=50, verbose_name='Respuesta Secreta')),
                ('question_3', models.CharField(max_length=100, verbose_name='3era Pregunta Secreta ')),
                ('answer_3', models.CharField(max_length=50, verbose_name=' Respuesta Secreta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.users')),
            ],
        ),
    ]
