# Generated by Django 5.1.3 on 2024-11-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemsInfo',
        ),
        migrations.AddField(
            model_name='items',
            name='exp',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='items',
            name='lot',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
