# Generated by Django 5.1.3 on 2024-11-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_delete_itemsinfo_items_exp_items_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='exp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='lot',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
