# Generated by Django 5.1.2 on 2024-12-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_1',
            field=models.CharField(max_length=80, verbose_name='Primera Pegunta Secreta'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_2',
            field=models.CharField(max_length=100, verbose_name='Segunda Pregunta Secreta'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_3',
            field=models.CharField(max_length=100, verbose_name='Tercera Pregunta Secreta '),
        ),
    ]
