# Generated by Django 5.1.2 on 2024-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_alter_questions_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=60, unique=True, verbose_name='Usuario'),
        ),
    ]
